#[default doc]
spring:
  application:
    name: anasheed
  profiles:
    active: local
server:
  port: 8080
---

#[local doc]
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/anasheed
    username: anasheed
    password: anasheed
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
app:
  s3:
    region: us-east-1
    bucket: anasheed-dev
    access-key: dummy
    secret-key: dummy
  jwt:
    secret: localdevsecret-min-32-chars-long-please-xxxx
    expiration-minutes: 60
logging:
  level:
    com.anasheed.app: DEBUG
---
#[prod doc]
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:?}
    username: ${DB_USER:?}
    password: ${DB_PASSWORD:?}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:?}

app:
  s3:
    region: ${AWS_REGION:?}
    bucket: ${AWS_S3_BUCKET:?}
    access-key: ${AWS_ACCESS_KEY_ID:?}
    secret-key: ${AWS_SECRET_ACCESS_KEY:?}
  jwt:
    secret: ${JWT_SECRET:?}
    expiration-minutes: 60

logging:
  level:
    com.anasheed.app: INFO
